[project]
name = "flet-basecomponents"
version = "0.1.0"
description = "Flet_BaseComponents is a reusable component library designed for Flet applications"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flet[all]==0.28.3",
]
